import { collectorsRegistry, defaultCollectors } from "../collectors";
import { ToolCapability, ToolCategory } from "../models/types";

type ToolFilter = {
  category?: ToolCategory;
  enabled?: boolean;
};

const collectorDetails: Record<string, Omit<ToolCapability, "name" | "displayName" | "description" | "category" | "source" | "executionMode" | "enabled">> = {
  domain: {
    inputs: ["domain", "url"],
    outputs: ["domain", "dns_record", "whois_record", "ssl_certificate", "reputation_signal"],
    acceptsTargetTypes: ["DOMAIN", "URL"],
    requiresApproval: false,
    parallelSafe: true,
    tags: ["built_in", "collector", "attack_surface", "default"],
    timeoutSeconds: 60
  },
  email: {
    inputs: ["email", "domain"],
    outputs: ["email", "breach_signal", "mx_record", "account_presence"],
    acceptsTargetTypes: ["EMAIL", "DOMAIN", "USERNAME"],
    requiresApproval: false,
    parallelSafe: true,
    tags: ["built_in", "collector", "identity", "default"],
    timeoutSeconds: 60
  },
  ip: {
    inputs: ["ip", "domain"],
    outputs: ["ip", "reverse_dns", "geo_location", "reputation_signal", "asn"],
    acceptsTargetTypes: ["IP", "DOMAIN", "URL"],
    requiresApproval: false,
    parallelSafe: true,
    tags: ["built_in", "collector", "network", "default"],
    timeoutSeconds: 60
  },
  web: {
    inputs: ["url", "domain"],
    outputs: ["website", "technology", "security_header", "subdomain"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    requiresApproval: false,
    parallelSafe: true,
    tags: ["built_in", "collector", "web", "default"],
    timeoutSeconds: 90
  },
  social: {
    inputs: ["username", "email", "domain"],
    outputs: ["social_account", "profile", "repository_signal"],
    acceptsTargetTypes: ["USERNAME", "EMAIL", "DOMAIN"],
    requiresApproval: false,
    parallelSafe: true,
    tags: ["built_in", "collector", "social", "default"],
    timeoutSeconds: 60
  },
  geo: {
    inputs: ["location", "ip", "domain"],
    outputs: ["location", "geocode", "nearby_business"],
    acceptsTargetTypes: ["IP", "DOMAIN", "USERNAME", "URL"],
    requiresApproval: false,
    parallelSafe: true,
    tags: ["built_in", "collector", "geo", "default"],
    timeoutSeconds: 60
  },
  media: {
    inputs: ["url", "file"],
    outputs: ["media_metadata", "exif_record", "ocr_text"],
    acceptsTargetTypes: ["URL"],
    requiresApproval: false,
    parallelSafe: false,
    tags: ["built_in", "collector", "media"],
    timeoutSeconds: 90
  },
  darkweb: {
    inputs: ["domain", "email", "username"],
    outputs: ["darkweb_signal", "leak_signal", "tor_reference"],
    acceptsTargetTypes: ["DOMAIN", "EMAIL", "USERNAME"],
    requiresApproval: true,
    parallelSafe: false,
    tags: ["built_in", "collector", "darkweb"],
    timeoutSeconds: 120
  }
};

const mcpCapabilities: ToolCapability[] = [
  {
    name: "amass",
    displayName: "Amass",
    description: "Domain and attack-surface discovery through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["subdomain", "domain_relationship"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "subdomain", "external_tool"],
    endpointPath: "/mcp/tools/recon/amass",
    timeoutSeconds: 180
  },
  {
    name: "subfinder",
    displayName: "Subfinder",
    description: "Passive subdomain discovery through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["subdomain"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "subdomain", "external_tool"],
    endpointPath: "/mcp/tools/recon/subfinder",
    timeoutSeconds: 120
  },
  {
    name: "httpx",
    displayName: "HTTPX",
    description: "Live web asset probing through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain", "subdomain", "url"],
    outputs: ["live_asset", "http_service", "technology"],
    acceptsTargetTypes: ["DOMAIN", "URL"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "web", "external_tool"],
    endpointPath: "/mcp/tools/recon/httpx",
    timeoutSeconds: 120
  },
  {
    name: "katana",
    displayName: "Katana",
    description: "Crawler and URL discovery through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["url", "domain"],
    outputs: ["url", "endpoint"],
    acceptsTargetTypes: ["DOMAIN", "URL"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "crawler", "external_tool"],
    endpointPath: "/mcp/tools/recon/katana",
    timeoutSeconds: 180
  },
  {
    name: "waymore",
    displayName: "Waymore",
    description: "Archive URL discovery through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain", "url"],
    outputs: ["url", "archived_url"],
    acceptsTargetTypes: ["DOMAIN", "URL"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "archive", "external_tool"],
    endpointPath: "/mcp/tools/recon/waymore",
    timeoutSeconds: 180
  },
  {
    name: "gau",
    displayName: "GAU",
    description: "Historical URL collection through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["url", "archived_url"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "archive", "external_tool"],
    endpointPath: "/mcp/tools/recon/gau",
    timeoutSeconds: 120
  },
  {
    name: "nmap",
    displayName: "Nmap",
    description: "Network service discovery through Network MCP.",
    category: "mcp",
    source: "Network MCP",
    executionMode: "mcp_gateway",
    inputs: ["ip", "domain"],
    outputs: ["port", "service", "host"],
    acceptsTargetTypes: ["IP", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["network", "ports", "external_tool"],
    endpointPath: "/mcp/tools/network/nmap",
    timeoutSeconds: 240
  },
  {
    name: "naabu",
    displayName: "Naabu",
    description: "Fast port discovery through Network MCP.",
    category: "mcp",
    source: "Network MCP",
    executionMode: "mcp_gateway",
    inputs: ["ip", "domain"],
    outputs: ["port", "host"],
    acceptsTargetTypes: ["IP", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["network", "ports", "external_tool"],
    endpointPath: "/mcp/tools/network/naabu",
    timeoutSeconds: 180
  },
  {
    name: "dnsx",
    displayName: "DNSX",
    description: "DNS resolution and enrichment through Network MCP.",
    category: "mcp",
    source: "Network MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain", "subdomain"],
    outputs: ["dns_record", "ip"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["network", "dns", "external_tool"],
    endpointPath: "/mcp/tools/network/dnsx",
    timeoutSeconds: 120
  },
  {
    name: "masscan",
    displayName: "Masscan",
    description: "High-speed port discovery through Network MCP.",
    category: "mcp",
    source: "Network MCP",
    executionMode: "mcp_gateway",
    inputs: ["ip", "cidr"],
    outputs: ["port", "host"],
    acceptsTargetTypes: ["IP"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["network", "ports", "external_tool", "high_intensity"],
    endpointPath: "/mcp/tools/network/masscan",
    timeoutSeconds: 300
  },
  {
    name: "nuclei",
    displayName: "Nuclei",
    description: "Template-based web finding discovery through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url", "live_asset"],
    outputs: ["finding", "vulnerability_signal", "technology"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["web", "finding", "external_tool"],
    endpointPath: "/mcp/tools/web/nuclei",
    timeoutSeconds: 240
  },
  {
    name: "whatweb",
    displayName: "WhatWeb",
    description: "Web technology fingerprinting through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url", "domain"],
    outputs: ["technology", "website"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["web", "technology", "external_tool"],
    endpointPath: "/mcp/tools/web/whatweb",
    timeoutSeconds: 120
  },
  {
    name: "wafw00f",
    displayName: "Wafw00f",
    description: "WAF fingerprinting through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url", "domain"],
    outputs: ["waf_signal", "technology"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["web", "waf", "external_tool"],
    endpointPath: "/mcp/tools/web/wafw00f",
    timeoutSeconds: 120
  },
  {
    name: "nikto",
    displayName: "Nikto",
    description: "Web server configuration checks through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url", "domain"],
    outputs: ["finding", "web_server_signal"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["web", "finding", "external_tool"],
    endpointPath: "/mcp/tools/web/nikto",
    timeoutSeconds: 240
  },
  {
    name: "sherlock",
    displayName: "Sherlock",
    description: "Username presence discovery through OSINT MCP.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["username"],
    outputs: ["social_account"],
    acceptsTargetTypes: ["USERNAME"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["osint", "social", "external_tool"],
    endpointPath: "/mcp/tools/osint/sherlock",
    timeoutSeconds: 180
  },
  {
    name: "holehe",
    displayName: "Holehe",
    description: "Email account presence checks through OSINT MCP.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["email"],
    outputs: ["account_presence"],
    acceptsTargetTypes: ["EMAIL"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["osint", "email", "external_tool"],
    endpointPath: "/mcp/tools/osint/holehe",
    timeoutSeconds: 180
  },
  {
    name: "theharvester",
    displayName: "theHarvester",
    description: "Email, host, and people discovery through OSINT MCP.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["email", "subdomain", "person"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["osint", "email", "people", "external_tool"],
    endpointPath: "/mcp/tools/osint/theharvester",
    timeoutSeconds: 180
  },
  {
    name: "phoneinfoga",
    displayName: "PhoneInfoga",
    description: "Phone number intelligence through OSINT MCP.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["phone"],
    outputs: ["phone_intelligence"],
    acceptsTargetTypes: ["PHONE"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["osint", "phone", "external_tool"],
    endpointPath: "/mcp/tools/osint/phoneinfoga",
    timeoutSeconds: 180
  },
  {
    name: "exiftool",
    displayName: "ExifTool",
    description: "Media metadata extraction through OSINT MCP.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["file", "url"],
    outputs: ["media_metadata", "exif_record"],
    acceptsTargetTypes: ["URL"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["osint", "media", "external_tool"],
    endpointPath: "/mcp/tools/osint/exiftool",
    timeoutSeconds: 120
  }
];

const expandedMcpCapabilities: ToolCapability[] = [
  {
    name: "dnsrecon",
    displayName: "DNSRecon",
    description: "DNS enumeration and record discovery through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["dns_record", "subdomain", "zone_signal"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "dns", "subdomain", "external_tool"],
    endpointPath: "/mcp/tools/recon/dnsrecon",
    timeoutSeconds: 180
  },
  {
    name: "fierce",
    displayName: "Fierce",
    description: "DNS reconnaissance and domain mapping through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["dns_record", "subdomain", "host"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "dns", "subdomain", "external_tool"],
    endpointPath: "/mcp/tools/recon/fierce",
    timeoutSeconds: 180
  },
  {
    name: "dnsenum",
    displayName: "DNSEnum",
    description: "DNS and name-server enumeration through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["dns_record", "subdomain", "name_server"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "dns", "subdomain", "external_tool"],
    endpointPath: "/mcp/tools/recon/dnsenum",
    timeoutSeconds: 180
  },
  {
    name: "waybackurls",
    displayName: "Waybackurls",
    description: "Historical URL discovery from public archives through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["url", "archived_url"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "archive", "url", "external_tool"],
    endpointPath: "/mcp/tools/recon/waybackurls",
    timeoutSeconds: 120
  },
  {
    name: "hakrawler",
    displayName: "Hakrawler",
    description: "Endpoint and link crawling through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["url", "domain"],
    outputs: ["url", "endpoint", "javascript_file"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "crawler", "web", "endpoint", "external_tool"],
    endpointPath: "/mcp/tools/recon/hakrawler",
    timeoutSeconds: 180
  },
  {
    name: "assetfinder",
    displayName: "Assetfinder",
    description: "Passive subdomain discovery through Recon MCP.",
    category: "mcp",
    source: "Recon MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["subdomain"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["recon", "subdomain", "osint", "external_tool"],
    endpointPath: "/mcp/tools/recon/assetfinder",
    timeoutSeconds: 120
  },
  {
    name: "rustscan",
    displayName: "RustScan",
    description: "Fast port discovery through Network MCP.",
    category: "mcp",
    source: "Network MCP",
    executionMode: "mcp_gateway",
    inputs: ["ip", "domain"],
    outputs: ["port", "host"],
    acceptsTargetTypes: ["IP", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["network", "ports", "external_tool", "high_intensity"],
    endpointPath: "/mcp/tools/network/rustscan",
    timeoutSeconds: 240
  },
  {
    name: "autorecon",
    displayName: "AutoRecon",
    description: "Comprehensive network enumeration orchestration through Network MCP.",
    category: "mcp",
    source: "Network MCP",
    executionMode: "mcp_gateway",
    inputs: ["ip", "domain"],
    outputs: ["service", "port", "host", "finding"],
    acceptsTargetTypes: ["IP", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["network", "ports", "service", "external_tool", "high_intensity"],
    endpointPath: "/mcp/tools/network/autorecon",
    timeoutSeconds: 600
  },
  {
    name: "enum4linux_ng",
    displayName: "enum4linux-ng",
    description: "SMB and Windows host enumeration through Network MCP.",
    category: "mcp",
    source: "Network MCP",
    executionMode: "mcp_gateway",
    inputs: ["ip", "domain"],
    outputs: ["host", "service", "share", "identity_signal"],
    acceptsTargetTypes: ["IP", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["network", "smb", "enumeration", "external_tool"],
    endpointPath: "/mcp/tools/network/enum4linux_ng",
    timeoutSeconds: 240
  },
  {
    name: "sslscan",
    displayName: "SSLScan",
    description: "TLS posture and certificate enumeration through Network MCP.",
    category: "mcp",
    source: "Network MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain", "ip", "url"],
    outputs: ["ssl_certificate", "tls_signal", "finding"],
    acceptsTargetTypes: ["DOMAIN", "IP", "URL"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["network", "tls", "certificate", "finding", "external_tool"],
    endpointPath: "/mcp/tools/network/sslscan",
    timeoutSeconds: 180
  },
  {
    name: "gobuster",
    displayName: "Gobuster",
    description: "Directory, file, DNS, and virtual-host discovery through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url", "domain"],
    outputs: ["endpoint", "directory", "subdomain"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["web", "content_discovery", "directory", "external_tool", "high_intensity"],
    endpointPath: "/mcp/tools/web/gobuster",
    timeoutSeconds: 300
  },
  {
    name: "ffuf",
    displayName: "FFUF",
    description: "Fast web content and endpoint discovery through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url", "domain"],
    outputs: ["endpoint", "directory", "http_signal"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["web", "content_discovery", "fuzzer", "external_tool", "high_intensity"],
    endpointPath: "/mcp/tools/web/ffuf",
    timeoutSeconds: 300
  },
  {
    name: "feroxbuster",
    displayName: "Feroxbuster",
    description: "Recursive web content discovery through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url"],
    outputs: ["endpoint", "directory", "http_signal"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["web", "content_discovery", "crawler", "external_tool", "high_intensity"],
    endpointPath: "/mcp/tools/web/feroxbuster",
    timeoutSeconds: 300
  },
  {
    name: "dirsearch",
    displayName: "Dirsearch",
    description: "Web path and directory discovery through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url"],
    outputs: ["endpoint", "directory", "http_signal"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["web", "content_discovery", "directory", "external_tool"],
    endpointPath: "/mcp/tools/web/dirsearch",
    timeoutSeconds: 300
  },
  {
    name: "arjun",
    displayName: "Arjun",
    description: "HTTP parameter discovery through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url"],
    outputs: ["parameter", "endpoint"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["web", "parameter", "endpoint", "external_tool"],
    endpointPath: "/mcp/tools/web/arjun",
    timeoutSeconds: 240
  },
  {
    name: "paramspider",
    displayName: "ParamSpider",
    description: "Parameter mining from archived URLs through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain"],
    outputs: ["parameter", "url", "archived_url"],
    acceptsTargetTypes: ["DOMAIN", "URL"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["web", "parameter", "archive", "external_tool"],
    endpointPath: "/mcp/tools/web/paramspider",
    timeoutSeconds: 240
  },
  {
    name: "wpscan",
    displayName: "WPScan",
    description: "WordPress version, plugin, theme, and exposure checks through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url"],
    outputs: ["technology", "finding", "cms_signal"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["web", "technology", "finding", "cms", "external_tool"],
    endpointPath: "/mcp/tools/web/wpscan",
    timeoutSeconds: 300
  },
  {
    name: "dalfox",
    displayName: "Dalfox",
    description: "XSS-oriented parameter reflection assessment through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url"],
    outputs: ["finding", "parameter", "xss_signal"],
    acceptsTargetTypes: ["URL"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["web", "finding", "parameter", "external_tool", "high_intensity"],
    endpointPath: "/mcp/tools/web/dalfox",
    timeoutSeconds: 300
  },
  {
    name: "jaeles",
    displayName: "Jaeles",
    description: "Template-based web finding checks through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url"],
    outputs: ["finding", "web_signal"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["web", "finding", "external_tool"],
    endpointPath: "/mcp/tools/web/jaeles",
    timeoutSeconds: 300
  },
  {
    name: "zap_baseline",
    displayName: "ZAP Baseline",
    description: "OWASP ZAP baseline web assessment through Web MCP.",
    category: "mcp",
    source: "Web MCP",
    executionMode: "mcp_gateway",
    inputs: ["url"],
    outputs: ["finding", "web_signal", "security_header"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["web", "finding", "security_header", "external_tool"],
    endpointPath: "/mcp/tools/web/zap_baseline",
    timeoutSeconds: 600
  },
  {
    name: "spiderfoot",
    displayName: "SpiderFoot",
    description: "OSINT collection and entity enrichment through OSINT MCP.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain", "ip", "email", "username"],
    outputs: ["osint_signal", "entity", "reputation_signal"],
    acceptsTargetTypes: ["DOMAIN", "IP", "EMAIL", "USERNAME"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["osint", "intelligence", "reputation", "external_tool"],
    endpointPath: "/mcp/tools/osint/spiderfoot",
    timeoutSeconds: 600
  },
  {
    name: "recon_ng",
    displayName: "Recon-ng",
    description: "Modular OSINT workspace automation through OSINT MCP.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["domain", "email", "username"],
    outputs: ["osint_signal", "subdomain", "email", "person"],
    acceptsTargetTypes: ["DOMAIN", "EMAIL", "USERNAME"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["osint", "intelligence", "people", "external_tool"],
    endpointPath: "/mcp/tools/osint/recon_ng",
    timeoutSeconds: 600
  },
  {
    name: "social_analyzer",
    displayName: "Social Analyzer",
    description: "Public profile and username intelligence through OSINT MCP.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["username", "email"],
    outputs: ["social_account", "profile", "identity_signal"],
    acceptsTargetTypes: ["USERNAME", "EMAIL"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["osint", "social", "identity", "external_tool"],
    endpointPath: "/mcp/tools/osint/social_analyzer",
    timeoutSeconds: 240
  },
  {
    name: "shodan_cli",
    displayName: "Shodan CLI",
    description: "Internet exposure lookup through OSINT MCP using local Shodan CLI credentials.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["ip", "domain"],
    outputs: ["service", "banner", "exposure_signal"],
    acceptsTargetTypes: ["IP", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["osint", "intelligence", "network", "external_tool"],
    endpointPath: "/mcp/tools/osint/shodan_cli",
    timeoutSeconds: 180
  },
  {
    name: "censys_cli",
    displayName: "Censys CLI",
    description: "Internet host and certificate intelligence through OSINT MCP.",
    category: "mcp",
    source: "OSINT MCP",
    executionMode: "mcp_gateway",
    inputs: ["ip", "domain"],
    outputs: ["service", "certificate", "exposure_signal"],
    acceptsTargetTypes: ["IP", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: true,
    tags: ["osint", "intelligence", "network", "certificate", "external_tool"],
    endpointPath: "/mcp/tools/osint/censys_cli",
    timeoutSeconds: 180
  },
  {
    name: "trivy",
    displayName: "Trivy",
    description: "Container, filesystem, repository, and IaC security inventory through Cloud MCP.",
    category: "mcp",
    source: "Cloud MCP",
    executionMode: "mcp_gateway",
    inputs: ["image", "path", "repository"],
    outputs: ["finding", "package", "vulnerability_signal", "iac_signal"],
    acceptsTargetTypes: ["URL", "DOMAIN", "UNKNOWN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["cloud", "container", "iac", "finding", "external_tool"],
    endpointPath: "/mcp/tools/cloud/trivy",
    timeoutSeconds: 600
  },
  {
    name: "checkov",
    displayName: "Checkov",
    description: "Infrastructure-as-code posture checks through Cloud MCP.",
    category: "mcp",
    source: "Cloud MCP",
    executionMode: "mcp_gateway",
    inputs: ["path", "repository"],
    outputs: ["iac_signal", "finding", "policy_signal"],
    acceptsTargetTypes: ["URL", "DOMAIN", "UNKNOWN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["cloud", "iac", "policy", "finding", "external_tool"],
    endpointPath: "/mcp/tools/cloud/checkov",
    timeoutSeconds: 600
  },
  {
    name: "terrascan",
    displayName: "Terrascan",
    description: "IaC security scanning through Cloud MCP.",
    category: "mcp",
    source: "Cloud MCP",
    executionMode: "mcp_gateway",
    inputs: ["path", "repository"],
    outputs: ["iac_signal", "finding", "policy_signal"],
    acceptsTargetTypes: ["URL", "DOMAIN", "UNKNOWN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["cloud", "iac", "policy", "finding", "external_tool"],
    endpointPath: "/mcp/tools/cloud/terrascan",
    timeoutSeconds: 600
  },
  {
    name: "prowler",
    displayName: "Prowler",
    description: "Cloud account security posture assessment through Cloud MCP.",
    category: "mcp",
    source: "Cloud MCP",
    executionMode: "mcp_gateway",
    inputs: ["cloud_account", "provider", "profile"],
    outputs: ["cloud_signal", "finding", "policy_signal"],
    acceptsTargetTypes: ["UNKNOWN", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["cloud", "policy", "finding", "external_tool", "high_intensity"],
    endpointPath: "/mcp/tools/cloud/prowler",
    timeoutSeconds: 900
  },
  {
    name: "kube_bench",
    displayName: "kube-bench",
    description: "Kubernetes CIS posture checks through Cloud MCP.",
    category: "mcp",
    source: "Cloud MCP",
    executionMode: "mcp_gateway",
    inputs: ["cluster", "path"],
    outputs: ["kubernetes_signal", "finding", "policy_signal"],
    acceptsTargetTypes: ["UNKNOWN", "DOMAIN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["cloud", "kubernetes", "policy", "finding", "external_tool"],
    endpointPath: "/mcp/tools/cloud/kube_bench",
    timeoutSeconds: 600
  },
  {
    name: "kube_hunter",
    displayName: "kube-hunter",
    description: "Kubernetes exposure assessment through Cloud MCP.",
    category: "mcp",
    source: "Cloud MCP",
    executionMode: "mcp_gateway",
    inputs: ["cluster", "ip", "domain"],
    outputs: ["kubernetes_signal", "finding", "exposure_signal"],
    acceptsTargetTypes: ["IP", "DOMAIN", "UNKNOWN"],
    enabled: true,
    requiresApproval: true,
    parallelSafe: false,
    tags: ["cloud", "kubernetes", "finding", "external_tool", "high_intensity"],
    endpointPath: "/mcp/tools/cloud/kube_hunter",
    timeoutSeconds: 600
  }
];

const apiCapabilities: ToolCapability[] = [
  {
    name: "virustotal",
    displayName: "VirusTotal",
    description: "External reputation enrichment for domains, IPs, URLs, and hashes.",
    category: "api",
    source: "Intelligence MCP",
    executionMode: "api_integration",
    inputs: ["domain", "ip", "url", "hash"],
    outputs: ["reputation_signal", "malware_signal"],
    acceptsTargetTypes: ["DOMAIN", "IP", "URL", "HASH"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: true,
    tags: ["intelligence", "reputation"]
  },
  {
    name: "shodan",
    displayName: "Shodan",
    description: "Internet exposure intelligence for IPs, domains, and services.",
    category: "api",
    source: "Intelligence MCP",
    executionMode: "api_integration",
    inputs: ["ip", "domain"],
    outputs: ["service", "banner", "exposure_signal"],
    acceptsTargetTypes: ["IP", "DOMAIN"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: true,
    tags: ["intelligence", "network"]
  },
  {
    name: "abuseipdb",
    displayName: "AbuseIPDB",
    description: "IP abuse and reputation intelligence.",
    category: "api",
    source: "Intelligence MCP",
    executionMode: "api_integration",
    inputs: ["ip"],
    outputs: ["reputation_signal", "abuse_signal"],
    acceptsTargetTypes: ["IP"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: true,
    tags: ["intelligence", "reputation"]
  },
  {
    name: "whois",
    displayName: "WHOIS",
    description: "Domain registration intelligence.",
    category: "api",
    source: "Intelligence MCP",
    executionMode: "api_integration",
    inputs: ["domain"],
    outputs: ["whois_record", "organization"],
    acceptsTargetTypes: ["DOMAIN"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: true,
    tags: ["intelligence", "registration"]
  },
  {
    name: "securitytrails",
    displayName: "SecurityTrails",
    description: "DNS and asset intelligence enrichment.",
    category: "api",
    source: "Intelligence MCP",
    executionMode: "api_integration",
    inputs: ["domain", "ip"],
    outputs: ["dns_record", "subdomain", "asset_signal"],
    acceptsTargetTypes: ["DOMAIN", "IP"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: true,
    tags: ["intelligence", "dns"]
  },
  {
    name: "hibp",
    displayName: "Have I Been Pwned",
    description: "Breach exposure checks for email identities.",
    category: "api",
    source: "Intelligence MCP",
    executionMode: "api_integration",
    inputs: ["email"],
    outputs: ["breach_signal", "exposed_credential_signal"],
    acceptsTargetTypes: ["EMAIL"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: true,
    tags: ["intelligence", "identity", "breach"]
  }
];

const browserCapabilities: ToolCapability[] = [
  {
    name: "browser_render",
    displayName: "Browser Render",
    description: "Dynamic page rendering and DOM extraction through Browser MCP.",
    category: "browser",
    source: "Browser MCP",
    executionMode: "browser_automation",
    inputs: ["url", "domain"],
    outputs: ["dom_snapshot", "page_text", "screenshot_reference"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: true,
    tags: ["browser", "playwright", "evidence"],
    endpointPath: "/mcp/tools/browser/render",
    timeoutSeconds: 120
  },
  {
    name: "browser_screenshot",
    displayName: "Browser Screenshot",
    description: "Screenshot capture through Browser MCP.",
    category: "browser",
    source: "Browser MCP",
    executionMode: "browser_automation",
    inputs: ["url", "domain"],
    outputs: ["screenshot_reference", "evidence"],
    acceptsTargetTypes: ["URL", "DOMAIN"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: true,
    tags: ["browser", "playwright", "evidence"],
    endpointPath: "/mcp/tools/browser/screenshot",
    timeoutSeconds: 120
  }
];

const internalCapabilities: ToolCapability[] = [
  {
    name: "correlate_findings",
    displayName: "Correlation Engine",
    description: "Generate normalized relationships between collected entities.",
    category: "internal",
    source: "ReconVault Backend",
    executionMode: "internal",
    inputs: ["investigation_id", "target"],
    outputs: ["relationship", "correlation_summary"],
    acceptsTargetTypes: ["DOMAIN", "URL", "IP", "EMAIL", "USERNAME"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: false,
    tags: ["internal", "correlation"]
  },
  {
    name: "risk_assessment",
    displayName: "Risk Assessment",
    description: "Apply ReconVault rule-based risk scoring to the current investigation target.",
    category: "internal",
    source: "ReconVault Backend",
    executionMode: "internal",
    inputs: ["target_id", "investigation_id"],
    outputs: ["risk_score", "risk_level", "risk_factors"],
    acceptsTargetTypes: ["DOMAIN", "URL", "IP", "EMAIL", "USERNAME"],
    enabled: true,
    requiresApproval: false,
    parallelSafe: false,
    tags: ["internal", "risk"]
  }
];

export class ToolRegistry {
  private buildCollectorCapabilities(): ToolCapability[] {
    return Object.keys(collectorsRegistry).map((name) => {
      const details = collectorDetails[name] || {
        inputs: ["target"],
        outputs: ["finding"],
        acceptsTargetTypes: ["DOMAIN", "URL", "IP", "EMAIL", "USERNAME"],
        requiresApproval: false,
        parallelSafe: true,
        tags: ["built_in", "collector"],
        timeoutSeconds: 60
      };

      return {
        name,
        displayName: `${name.charAt(0).toUpperCase()}${name.slice(1)} Collector`,
        description: `Built-in ReconVault ${name} intelligence collector.`,
        category: "collector",
        source: "ReconVault Collector",
        executionMode: "collector",
        enabled: true,
        ...details,
        tags: defaultCollectors.includes(name) ? Array.from(new Set([...details.tags, "default"])) : details.tags
      };
    });
  }

  list(filter: ToolFilter = {}): ToolCapability[] {
    let tools = [
      ...this.buildCollectorCapabilities(),
      ...mcpCapabilities,
      ...expandedMcpCapabilities,
      ...apiCapabilities,
      ...browserCapabilities,
      ...internalCapabilities
    ];

    if (filter.category) tools = tools.filter((tool) => tool.category === filter.category);
    if (filter.enabled !== undefined) tools = tools.filter((tool) => tool.enabled === filter.enabled);
    return tools;
  }

  get(name: string): ToolCapability | undefined {
    const normalized = String(name || "").toLowerCase();
    return this.list().find((tool) => tool.name.toLowerCase() === normalized);
  }

  getToolContext() {
    const collectors = this.list({ category: "collector" });
    const mcpTools = this.list({ category: "mcp" });
    const apiIntegrations = this.list({ category: "api" });
    const browserCapabilities = this.list({ category: "browser" });
    const internalTools = this.list({ category: "internal" });

    return {
      collectors,
      mcp_tools: mcpTools,
      api_integrations: apiIntegrations,
      browser_capabilities: browserCapabilities,
      internal_tools: internalTools,
      all_tools: [...collectors, ...mcpTools, ...apiIntegrations, ...browserCapabilities, ...internalTools]
    };
  }

  validateStepTool(toolName: string): { valid: boolean; tool?: ToolCapability; error?: string } {
    const tool = this.get(toolName);
    if (!tool) return { valid: false, error: `Unknown tool: ${toolName}` };
    if (!tool.enabled) return { valid: false, tool, error: `Tool is disabled: ${toolName}` };
    return { valid: true, tool };
  }
}

export const toolRegistry = new ToolRegistry();
